eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: order
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: nmfz
    password: 123456
    url:  jdbc:mysql://120.79.28.50:3307/nmfzTest?useUnicode=true&characterEncoding=UTF-8
env:
  env   
