eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: product
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: nmfz
    password: 123456
    url:  jdbc:mysql://120.79.28.50:3306/nmfzTest?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15s
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  port: 8766



